const NOT_FOUND_STATUS = 404;
const INVALID_STATUS = 400;
const SERVER_DEFAULT_STATUS = 500;
const TOKEN_STATUS = 401;
const ACCESS_STATUS = 403;
const REGISTER_STATUS = 409;

module.exports = {
  NOT_FOUND_STATUS,
  INVALID_STATUS,
  SERVER_DEFAULT_STATUS,
  TOKEN_STATUS,
  ACCESS_STATUS,
  REGISTER_STATUS,
};
